#version 450

layout(std430, binding = 0) readonly buffer InputA
{
	float input_a[];
};

layout(std430, binding = 1) readonly buffer InputB
{
	float input_b[];
};

layout(std430, binding = 2) writeonly buffer Output
{
	float output[];
};

layout(push_constant) uniform PushConstants
{
	uint n_elements;
} pc;

layout(local_size_x = 256) in;

void main()
{
	uint idx = gl_GlobalInvocationID.x;

	if (idx >= pc.n_elements)
		return;

	output[idx] = input_a[idx] + input_b[idx];
}
