#version 450

layout(std430, binding = 0) readonly buffer GradInputA
{
	float grad_input_a[];
};

layout(std430, binding = 1) readonly buffer GradInputB
{
	float grad_input_b[];
};

layout(std430, binding = 2) writeonly buffer GradOutput
{
	float grad_output[];
};

layout(push_constant) uniform PushConstants {
	uint n_elements;
} pc;

layout(local_size_x = 256) in;

void main()
{
	uint idx = gl_GlobalInvocationID.x;

	if (idx >= pc.n_elements)
		return;

	grad_output[idx] = grad_input_a[idx] + grad_input_b[idx];
}
