#version 450
#extension GL_KHR_shader_subgroup_basic : enable
#extension GL_KHR_shader_subgroup_arithmetic : enable
#extension GL_EXT_shader_atomic_float : enable

layout(std430, binding = 0) readonly buffer Weights
{
	float weights[];
};
layout(std430, binding = 1) readonly buffer Input_tensor
{
	float input_tensor[];
};
layout(std430, binding = 2) writeonly buffer Output_tensor
{
	float output_tensor[];
};

layout(std430, binding = 3) writeonly buffer resultsBuffer
{
	vec3 results[];
};


layout(push_constant) uniform PushConstants {
	uint c_in;
	uint c_out;
	uint img_size_in;
	uint img_size_out;
} c;


shared float sg_partials[4];
shared float total_acc;

//==================================================
// Layout
//

layout (local_size_x = 32, local_size_y = 4, local_size_z = 1) in;
	//gl_WorkGroupSize.x
	//gl_WorkGroupID.x

void main()
{

	uint ix = gl_LocalInvocationID.x;
	uint iy = gl_LocalInvocationID.y;
	uint id = ix + (iy * 32);

	ivec2 pos_in = ivec2(gl_WorkGroupID.x * 2, gl_WorkGroupID.y * 2);
	ivec2 pos_out = ivec2(gl_WorkGroupID.x, gl_WorkGroupID.y);
	
	float thread_acc = 0; //accumulate one output channel per thread

	if(gl_WorkGroupID.x == 0 && gl_WorkGroupID.y == 0)
		results[id].x = input_tensor[id];

	for(int i=0; i<128; i++) //loop over input channels
	{
		for(int x=0;x<16;x++) //iterate over each kernel cell. 16 spatial cells -> one output channel
		{
			uint kx = x % 4;
			uint ky = x / 4;

			float in_activation = input_tensor[(gl_WorkGroupID.z * 128 * c.img_size_in * c.img_size_in) + 
				(i * c.img_size_in * c.img_size_in) + pos_in.x + kx +
				(pos_in.y + ky) * c.img_size_in];

			//if(gl_WorkGroupID.x == 0 && gl_WorkGroupID.y == 0 &&  i == 5 && x == 0)
				//results[id].x = kx;
			//	results[id].x = in_activation;

			float my_weight = weights[(id*128*4*4) + i * (4*4) + x];

			//if(gl_WorkGroupID.x == 0 && gl_WorkGroupID.y == 0 && k == 0 && i == 13 && x == 0)
			//	results[id].x = my_weight;

			thread_acc += my_weight * in_activation;
			
		}	
	}

	//if(gl_WorkGroupID.x == 0 && gl_WorkGroupID.y == 0)
	//			results[id].x = thread_acc;

	//write channel out

	output_tensor[(gl_WorkGroupID.z * 128 * c.img_size_out * c.img_size_out) + 
		(id * c.img_size_out * c.img_size_out) + 
		(pos_out.y * c.img_size_out) + pos_out.x ] = thread_acc;

	return;
}