#version 450
#extension GL_KHR_shader_subgroup_basic : enable
#extension GL_KHR_shader_subgroup_arithmetic : enable

layout(std430, binding = 0) readonly buffer Input
{
	float input_b[];
};

layout(std430, binding = 1) readonly buffer Codebook
{
	float codebook[];
};

layout(std430, binding = 2) writeonly buffer Output
{
	float output_b[];
};

layout(std430, binding = 3) writeonly buffer Indices
{
	uint indices[];
};

layout(std430, binding = 4) writeonly buffer LossBuffer
{
	float loss_b[];
};

layout(push_constant) uniform PushConstants {
	uint n_vectors;
} pc;

layout(local_size_x = 128) in;

shared float sg_partials[4];
shared float best;
shared uint ret;

void main()
{
	uint id = gl_LocalInvocationID.x;

	uint H = 8;
	uint W = 8;
	uint N = gl_WorkGroupID.x / (H * W);
	uint hw = gl_WorkGroupID.x % (H * W);
	uint h = hw / W;
	uint w = hw % W;

	if(id==0)
	{
		best = 0xFFFF;
	}
	barrier();

	//each thread owns one channel
	//
	float x = input_b[(N * 128 * H * W) + (id * H * W) + (h * W) + w];

	//iterate over the codebook
	//
	for(uint j=0; j<pc.n_vectors; j++)
	{
		//each thread computes an element-by-element squared difference
		//
		float r = codebook[j * 128 + id] - x;
		r = r * r;

		//compute a sum (reduction)
		//
		float s = subgroupAdd(r);

		if(subgroupElect())
			sg_partials[gl_SubgroupID] = s;

		barrier();

		float loss = 0.0;

		if(id == 0)
		{
			for(int i=0; i<4; i++)
				loss += sg_partials[i];

			if(loss < best)
			{
				best = loss;
				ret = j;
			}
		}

		barrier();
	}

	//one value per spatial position
	if(id == 0)
	{
		indices[(N * H * W) + (h * W) + w] = ret;
		loss_b[(N * H * W) + (h * W) + w] = best;
	}

	barrier();

	// each thread writes its channel from the winning codebook vector
	output_b[(N * 128 * H * W) + (id * H * W) + (h * W) + w] = codebook[ret * 128 + id];
}