#version 450

layout(std430, binding = 0) buffer InputBuffer
{
	float input_b[];
};

layout(std430, binding = 1) buffer OutputBuffer
{
	float output_b[];
};

layout(push_constant) uniform PushConstants
{
	uint n;
	uint c;
	uint h;
	uint w;
} pc;

layout(local_size_x = 256) in;

void main()
{
	uint idx   = gl_GlobalInvocationID.x;
	uint total = pc.n * pc.c * pc.h * pc.w;

	if (idx >= total)
		return;

	float y =  1.0 / (1.0 + exp(-input_b[idx]));

	output_b[idx] = y;
}
